version: 2.1

jobs:
  test_a:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - checkout
      - run:
          name: "run A tests"
          command: "echo running A tests"
  test_b:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - checkout
      - run: |
          if [ "$CIRCLE_BRANCH" = "test" ]; then
            echo "no need to run B tests"
            circleci-agent step halt
          fi
      - run:
          name: "run B tests"
          command: "echo running B tests"
  deploy:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - checkout
      - run:
          name: "deploy"
          command: "echo deploying"


workflows:
  main-workflow:
    jobs:
      - test_a
      - test_b
      - deploy:
          requires:
            - test_a
            - test_b
