version: 2.1

jobs:
  test_a:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "run A tests"
          command: "echo running A tests"
  test_b:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "run B tests"
          command: "echo running B tests"
  deploy:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "deploy"
          command: "echo deploying"


# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  main-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - test_a
      - test_b
      - deploy:
          requires:
            - test_a
            - test_b